package org.conscrypt
// Gradle mostly uses Java os.arch names for architectures which feeds into default
// targetPlatform names.  Notable exception Gradle 6.9.x reports MacOS/ARM as
// arm-v8.
//
// The Maven osdetector plugin (which we recommend to developers) uses different
// arch names, so that's what we need for artifacts.
//
// This class encapsulates both naming schemes as well as other per-platform information
// about native builds, more of which will migrate in here over time.
import org.gradle.nativeplatform.platform.NativePlatform

enum NativeBuildInfo {
    WINDOWS_X86_64("windows", "x86_64"),
    LINUX_X86_64("linux", "x86_64"),
    MAC_X86_64("osx", "x86_64") {
        String libDir() {
            "build.x86"
        }
    },
    MAC_AARCH64("osx", "aarch_64") {
        String libDir() {
            "build.arm"
        }
    };

    static String buildDir = "FIXME" // See below
    static void setBuildDir(String dir) {
        buildDir = dir
    }

    public final String os
    public final String arch

    // Maps osdetector arch to Gradle equivalent.
    private static final gradleArchMap = [
            "aarch_64": "aarch64",
            "x86_64" : "x86-64",
    ]

    NativeBuildInfo(String os, String arch) {
        this.os = os
        this.arch = arch
    }

    // Classifier as generated by Maven osdetector.
    String mavenClassifier() {
        "${os}-${arch}"
    }

    // Gradle equivalent to Maven arch
    String gradleArch() {
        gradleArch(arch)
    }

    // Output directory for native resources
    String nativeResourcesDir() {
        "$buildDir/${mavenClassifier()}/native-resources"
    }

    // Directory for native resources inside final jar.
    String jarNativeResourcesDir() {
        nativeResourcesDir() + '/META-INF/native'
    }

    // Target platform identifier as used by Gradle
    String targetPlatform() {
        "${os}_${gradleArch()}"
    }

    String libDir() {
        "build64"
    }

    static String gradleArch(String arch) {
        gradleArchMap.get(arch)
    }

    static NativeBuildInfo findForGradle(String os, String arch) {
        values().find {
            it.os == os && it.gradleArch() == arch
        }
    }

    static NativeBuildInfo find(String os, String arch) {
        values().find {
            it.os == os && it.arch == arch
        }
    }

    static NativeBuildInfo find(NativePlatform targetPlatform) {
        String targetOS = targetPlatform.operatingSystem.name
        String targetArch = targetPlatform.architecture.name
        def result = findForGradle(targetOS, targetArch)
        assert result != null : "Unknown target platform: ${targetOS}-${targetArch}"
        result
    }

    static findAll(String os) {
        values().findAll {
            it.os == os
        }
    }
}
